FILEWORD MACRO DATA1
    MOV BX,OFFSET DATA1
    SUB CH,CH
    MOV CL,[BX]+1
    MOV WORDS,CX 
    ENDM
    
PRINT MACRO DATA2
    MOV AH,09H
    MOV DX,OFFSET DATA2
    INT 21H
    ENDM

DATAS SEGMENT
    ;此处输入数据段代码
     ORG 0010H
MESSAGE DB 'PLEASE ENTER THE NAME OF FILE:',CR,LF,'$'
MESSAGE2 DB CR,LF,'PLEASE ENTER THE CONTENT:',CR,LF,'$'   
ADDRESS DB 10,?,10 DUP(00)
LONG    DB ?
BUF     DB 100,?,100 DUP(00)
EMESSAGE DB 0AH,'ERROR!','$'
SMESSAGE DB 0AH,'SUCCESS!','$'
HANDLE DW ?
WORDS  DW ?
NUMBER DB 0
ORG 1000H
MEMONAME DB 100 DUP('$')
ORG 1800H
NAMESTART DB 0
NAMEEND   DB 0
ORG 2000H
COUNTLIST DB 100 DUP(00)
MEMOCOUNT DB 0
ORG 3000H
NAMEROW DB 0
NAMECOUNT DB 0

FILENAME DB 'AAA.TXT',0

CR EQU 0DH
LF EQU 0AH
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
MAIN PROC FAR
    MOV AX,DATAS
    MOV DS,AX
    ;此处输入代码段代码
   
    ;输入文件标题
    PRINT MESSAGE
    MOV AH,0AH
    MOV DX,OFFSET ADDRESS
    INT 21H
    
    ;将输入缓冲区中的0DH换为00H
    FILEWORD ADDRESS
    SUB CH,CH
    MOV SI,CX
    MOV BYTE PTR[BX+SI]+2,00
    
    ;获取文件名到00处结束，新建文件
    MOV DX,OFFSET ADDRESS
    INC DX
    INC DX
    MOV CX,0
    MOV AH,3CH
    INT 21H
    JC ERROR2
    MOV HANDLE,AX
    MOV AH,MEMOCOUNT
    INC AH
    MOV MEMOCOUNT,AH
    
    ;将文件名存入MEMONAME中
     MOV DI,OFFSET ADDRESS
     INC DI
     SUB CX,CX
     MOV CL,[DI]
     MOV NUMBER,CL
     INC DI
     MOV SI,OFFSET MEMONAME
     SUB BX,BX
     MOV BL,NAMESTART
NAMELOOP:         
     MOV AL,[DI]
     MOV [SI+BX],AL
     INC DI
     INC SI
     DEC CX
     CMP CX,0
     JNE NAMELOOP
     INC SI
     MOV AL,'$'
     MOV [SI+BX],AL
     
     ;将文件名长度存入COUNTLIST
     SUB BX,BX
     MOV SI,OFFSET COUNTLIST
     MOV BL,MEMOCOUNT
     MOV AL,NUMBER
     MOV BYTE PTR[SI+BX],AL
     
     SUB BX,BX
     MOV SI,OFFSET COUNTLIST
     MOV BL,MEMOCOUNT
     MOV BH,BYTE PTR[SI+BX] ;求出COUNTLIST[MEMOCOUNT]
     ADD BH,NAMESTART
     MOV NAMEEND,BH;求出当前MEMONAME的结束处
     ADD BH,2
     MOV NAMESTART,BH;求出下一个MEMONAME的开始处
     
    
    
    
    
 
    ;输入文件内容
    PRINT MESSAGE2
    MOV AH,0AH
    MOV DX,OFFSET BUF
    INT 21H
    
    ;获取输入内容字数
    FILEWORD BUF
    MOV BX,HANDLE
    MOV CX,WORDS
    MOV DX,OFFSET BUF
    INC DX
    INC DX
    MOV AH,40H
    INT 21H
    JC ERROR2
    
    ;关闭文件
    MOV BX,HANDLE
    MOV AH,3EH
    INT 21H
    JC ERROR2
    PRINT SMESSAGE


    MOV AL,3
    MOV NAMEROW,AL
    MOV BL,40
    SUB CX,CX
    MOV CL,MEMOCOUNT
    MOV NAMECOUNT,CL
    MOV SI,OFFSET COUNTLIST
LISTLOOP:
    MOV AH,02H
    MOV BH,00
    MOV DH,NAMEROW
    MOV DL,40  ;设置光标位置
    INT 10H
    
    ;显示已有备忘录名称
    ;DISPLAY SMESSAGE
    
    MOV AH,09H
    MOV DX,OFFSET MEMONAME
    ADD DL,NAMESTART
    INT 21H
    MOV BL,NAMECOUNT
    DEC BL
    MOV NAMECOUNT,BL
    SUB BH,BH
    MOV BH,BYTE PTR[SI+BX]
    MOV AH,NAMESTART
    DEC AH
    SUB AH,BH
    MOV NAMESTART,AH
    
    MOV AL,NAMEROW
    ADD AL,2
    MOV NAMEROW,AL
    DEC CX
    CMP CX,0
    JNE LISTLOOP
    
    MOV DX, OFFSET FILENAME
    MOV AL,0
    MOV AH,3DH
    INT 21H
    JC ERROR2
    MOV HANDLE,AX
    MOV BX,AX
    MOV CX,255
    MOV DX,OFFSET BUF
    MOV AH,3FH
    INT 21H
    JC ERROR2
    MOV BX,AX
    MOV BUF[BX],'$'
    MOV DX,OFFSET BUF
    MOV AH,09H
    INT 21H
    MOV BX,HANDLE
    MOV AH,3EH
    INT 21H
    JNC END1
    
    
    ;删除文件
    ;MOV DX,OFFSET ADDRESS
    ;INC DX
    ;INC DX
    ;MOV AH,41H
    ;INT 21H
    ;JC  ERROR2
    ;PRINT SMESSAGE
    ;JMP END1
 
ERROR2:
    PRINT EMESSAGE
    
    
    
END1:
    MOV AH,4CH
    INT 21H
    
MAIN ENDP
   
CODES ENDS
    END START









