CURSOR MACRO ROW,COLUMN
       MOV AH,02H
       MOV BH,00
       MOV DH,ROW
       MOV DL,COLUMN  ;设置光标位置
       INT 10H
       ENDM
DISPLAY MACRO STRING
       MOV AH,09H
       MOV DX,OFFSET STRING  ;装入字符串地址
       INT 21H
       ENDM
FILL MACRO ROW_START,COL_START,ROW_END,COL_END,COLOR
       LOCAL START1,AGAIN
       MOV DX,ROW_START
START1:
       MOV CX,COL_START
AGAIN:
       MOV AH,0CH
       MOV AL,COLOR   ;写像素，AL中存放像素值
       INT 10H
       INC CX
       CMP CX,COL_END ;画一条水平线
       JNE AGAIN
       INC DX
       CMP DX,ROW_END ;增加行值画水平线，以此画出矩形
       JNE START1
       ENDM

CLEARSRC MACRO
    MOV AX,0600H           ;清除屏幕
    MOV BH,07
    MOV CX,0
    MOV DX,184FH
    INT 10H
    ENDM      

FRAME MACRO ROW_START,COL_START,ROW_END,COL_END,COLOR ;画出矩形框
      LOCAL ROWCOL1,ROWCOL2,ROWCOL3,ROWCOL4
      MOV DX,ROW_START
      MOV CX,COL_START
ROWCOL1:
      MOV AH,0CH
      MOV AL,COLOR
      INT 10H
      INC CX
      CMP CX,COL_END
      JNE ROWCOL1
      
      MOV CX,COL_START
ROWCOL2:
      MOV AH,0CH
      MOV AL,COLOR
      INT 10H
      INC DX
      CMP DX,ROW_END
      JNE ROWCOL2
      
      MOV DX,ROW_END
      MOV CX,COL_START
ROWCOL3:
      MOV AH,0CH
      MOV AL,COLOR
      INT 10H
      INC CX
      CMP CX,COL_END
      JNE ROWCOL3
      
      MOV DX,ROW_START
      MOV CX,COL_END
ROWCOL4:
      MOV AH,0CH
      MOV AL,COLOR
      INT 10H
      INC DX
      CMP DX,ROW_END
      JNE ROWCOL4       
      
      ENDM

FILEWORD MACRO DATA1
      MOV BX,OFFSET DATA1
      SUB CH,CH
      MOV CL,[BX]+1
      MOV WORDS,CX
      ENDM
             

DATAS SEGMENT
    ;此处输入数据段代码 
CR EQU 0DH
LF EQU 0AH    
    
MESSAGE_1 DB 'Welcome!','$'
MESSAGE_2 DB 'ENTER','$'
MESSAGE_3 DB 'NEWMEMO','$'
MESSAGE_4 DB 'MODEL2','$'
MESSAGE_5 DB 'MODEL3','$'
MESSAGE_6 DB 'MODEL4','$'
MESSAGE_7 DB 'EXIT','$'
MESSAGE_8 DB 'PRESS ENTER TO ENTER','$'
OLDVIDEO  DB ?
NEWVIDEO  DB 12H
WHEATHERIN DB ?

TITLETEXT DB 'TITLE:','$'
CONTEXTTEXT DB 'CONTEXT:','$'
SAVETEXT DB 'SAVE','$'
BACKTEXT DB 'BACK','$'
SMESSAGE DB 'SUCCESS!','$'
TITLEMESSAGE DB 'PLEASE ENTER THE NAME OF FILE','$'
CONTEXTMESSAGE DB 'PLEASE ENTER THE CONTENT','$'
INFORMATION DB 'INFO:','$'
ADDRESS DB 10,?,10 DUP(00)
BUF     DB 100,?,100 DUP(00)
LONG DB ?
HANDLE DW ?
WORDS  DW ?
ERRORTIMES DB 0
ERRORMESSAGE DB 'ERROR!PLEASE TRY AGAIN!','$'

DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
START:
MAIN PROC 
    MOV AX,DATAS
    MOV DS,AX
    ;此处输入代码段代码
FIRST:
    MOV CX,33144
    CALL TDELAY            ;此处延迟十分重要！！调试时没有这个延迟导致页面生成不对
    MOV AH,0FH
    INT 10H                ;获得当前视频模式
    MOV OLDVIDEO,AL        ;保存当前视频模式
    MOV AX,0600H           ;清除屏幕
    MOV BH,07
    MOV CX,0
    MOV DX,184FH
    INT 10H
    MOV AH,00H             ;设置新的视频模式
    MOV AL,NEWVIDEO
    INT 10H
    CURSOR 0,0             ;设置光标在0,0
    FILL 150,250,250,350,4 ;在150,250处画一个红框
    CURSOR 6,194     
    DISPLAY MESSAGE_1
    CURSOR 8,27
    DISPLAY MESSAGE_8
    CURSOR 12,195
    DISPLAY MESSAGE_2
    MOV AX,0000H     ;初始化鼠标
    INT 33H
    MOV AX,01H
    INT 33H          ;检查鼠标光标
BACK:
    MOV AX,03H       ;检查是否按下鼠标
    INT 33H
    CMP BX,0001H     ;现在在cx=列dx=行的位置
    JNE BACK         ;检查左键是否按下
    CMP CX,250       ;看是否在框的右边
    JB NOT_INSIDE
    CMP CX,350
    JA NOT_INSIDE
    CMP DX,150
    JB NOT_INSIDE
    CMP DX,250
    JA NOT_INSIDE     ;检查是否在框中

SECONDPAINT:        
    MOV AX,0600H           ;清除屏幕
    MOV BH,07
    MOV CX,0
    MOV DX,184FH
    INT 10H
    
    MOV AH,00H              ;设置新的视频模式
    MOV AL,NEWVIDEO
    INT 10H
    
    CURSOR 0,0
    FILL 30,50,80,200,4
    CURSOR 3,12
    DISPLAY MESSAGE_3
    FILL 110,50,160,200,4
    CURSOR 8,12
    DISPLAY MESSAGE_4
    FILL 190,50,240,200,4
    CURSOR 13,12
    DISPLAY MESSAGE_5
    FILL 270,50,320,200,4
    CURSOR 18,12
    DISPLAY MESSAGE_6
    FILL 400,500,450,600,4
    CURSOR 26,67
    DISPLAY MESSAGE_7
    
    MOV AX,0000H
    INT 33H                  ;初始化鼠标
    MOV AX,01H
    INT 33H     
BACK2:
    MOV AX,03H                ;检查鼠标
    INT 33H
    CMP BX,0001H
    JNE BACK2
    CMP CX,50
    JB  MODEL2
    CMP DX,30
    JB  MODEL2
    CMP CX,200
    JA  MODEL2
    CMP DX,80
    JA  MODEL2           ;判断是否在模块一中
    CLEARSRC
    MOV CX,33144
    CALL TDELAY
    JMP MODEL1
    ;JMP SECONDPAINT
MODEL2:   
    CMP CX,50
    JB  MODEL3
    CMP DX,110
    JB  MODEL3
    CMP CX,200
    JA  MODEL3
    CMP DX,160
    JA  MODEL3
    ;CALL MODEL2               ;判断是否在模块2
MODEL3:    
    CMP CX,50
    JB  MODEL4
    CMP DX,190
    JB  MODEL4
    CMP CX,200
    JA  MODEL4
    CMP DX,240
    JA  MODEL4
    ;CALL MODEL3                ;判断是否在模块3中
MODEL4:    
    CMP CX,50
    JB  EXITMAIN
    CMP DX,270
    JB  EXITMAIN
    CMP CX,200
    JA  EXITMAIN
    CMP DX,320
    JA  EXITMAIN
    ;CALL MODEL4                 ;判断是否在模块4中
EXITMAIN:   
    CMP CX,500
    JB  NOT_INSIDE2
    CMP DX,400
    JB  NOT_INSIDE2
    CMP CX,600
    JA  NOT_INSIDE2
    CMP DX,450
    JA  NOT_INSIDE2
    JMP FIRST
    
 
    MODEL1:
     
     CLEARSRC               ;清除屏幕
     MOV AH,00            ;设置视频模式
     MOV AL,NEWVIDEO
     INT 10H
     
     CURSOR 0,0
     FRAME 70,130,110,550,4
     FRAME 150,130,400,550,4
     FRAME 420,150,450,250,4
     FRAME 420,430,450,530,4
     
     CURSOR 5,10
     DISPLAY TITLETEXT
     CURSOR 10,8
     DISPLAY CONTEXTTEXT
     CURSOR 8,70
     DISPLAY INFORMATION
     CURSOR 27,23
     DISPLAY SAVETEXT
     CURSOR 27,58
     DISPLAY BACKTEXT
     
     CURSOR 0,0
     MOV AX,0000H      ;初始化鼠标
     INT 33H
     
NEWBACK:
     MOV AX,01H
     INT 33H           ;检查鼠标光标
     MOV AX,03H        ;检查是否按下鼠标
     INT 33H
     CMP BX,0001H      ;现在在cx=列dx=行的位置
     JNE NEWBACK       ;检查左键是否按下
     CMP DX,70
     JB  NEWBACK2
     CMP DX,110
     JA  NEWBACK2
     CMP CX,130
     JB  NEWBACK2
     CMP CX,550
     JA  NEWBACK2
     
     CURSOR 3,16
     DISPLAY TITLEMESSAGE
     ;获取标题
     CURSOR 5,18
     MOV AH,0AH
     MOV DX,OFFSET ADDRESS
     INT 21H                  
     ;将输入缓冲区中的0DH换为00H
     FILEWORD ADDRESS
     SUB CH,CH
     MOV SI,CX
     MOV BYTE PTR[BX+SI]+2,00
     ;获取文件名到00结束，新建文件
     MOV DX,OFFSET ADDRESS
     INC DX
     INC DX
     MOV CX,0
     MOV AH,3CH
     INT 21H
     JC  ERROR
     MOV ERRORTIMES,0
     MOV HANDLE,AX
     JMP NEWBACK
          
NEWBACK2:     
     CMP DX,150
     JB  NEWBACK3
     CMP DX,400
     JA  NEWBACK3
     CMP CX,130
     JB  NEWBACK3
     CMP CX,550
     JA  NEWBACK3
     
     CURSOR 8,16
     DISPLAY CONTEXTMESSAGE
     ;输入文件内容
     CURSOR 10,18
     MOV AH,0AH
     MOV DX,OFFSET BUF
     INT 21H
     
     ;获取输入内容字数
     FILEWORD BUF
     MOV BX,HANDLE
     MOV CX,WORDS
     MOV DX,OFFSET BUF
     INC DX
     INC DX
     MOV AH,40H
     INT 21H
     JC ERROR
     MOV ERRORTIMES,0
     ;关闭文件
     MOV BX,HANDLE
     MOV AH,3EH
     INT 21H
     JC ERROR
     JMP NEWBACK

NEWBACK3:     
     CMP DX,420
     JB  NEWBACK4
     CMP DX,450
     JA  NEWBACK4
     CMP CX,150
     JB  NEWBACK4
     CMP CX,250
     JA  NEWBACK4
     CMP ERRORTIMES,0
     JA  ERRORM
     CURSOR 10,70
     DISPLAY SMESSAGE
     JMP NEWBACK4
ERROR:
     INC ERRORTIMES
     JMP NEWBACK     
ERRORM:
     CURSOR 10,70
     DISPLAY ERRORMESSAGE

NEWNEXT:
     MOV CX,33144
     CALL TDELAY
     MOV AX,0600H
     MOV BH,0
     MOV CX,2020H
     MOV DX,2330H
     INT 10H
     JMP NEWBACK
     
     
     
NEWBACK4:
     CMP DX,420
     JB  NEWBACK
     CMP DX,450
     JA  NEWBACK
     CMP CX,430
     JB  NEWBACK
     CMP CX,530
     JA  NEWBACK
     JMP SECONDPAINT
    

NOT_INSIDE:
    JMP BACK
    
NOT_INSIDE2:
   
    MOV AH,4CH
    INT 21H
MAIN ENDP

TDELAY PROC NEAR
     PUSH AX
W1:  
     IN  AL,61H
     AND AL,00010000B
     CMP AL,AH
     JE  W1
     MOV AH,AL
     LOOP W1
     POP AX
     RET
TDELAY ENDP






CODES ENDS
    END START







